law: OR
article: 734
article_suffix: b
title: Darlehen und Kredite an den Verwaltungsrat, die Geschäftsleitung und den Beirat
sr_number: '220'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/27/317_321_377/de#art_734b
lexfind_url: ''
in_force_since: ''
layers: {}
