law: ZGB
article: 740
article_suffix: ''
title: Nach kantonalem Recht und Ortsgebrauch
sr_number: '210'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/24/233_245_233/de#art_740
lexfind_url: ''
in_force_since: ''
layers: {}
