law: OR
article: 329
article_suffix: e
title: Urlaub für ausserschulische Jugendarbeit
sr_number: '220'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/27/317_321_377/de#art_329e
lexfind_url: ''
in_force_since: ''
layers: {}
