law: StGB
article: 2
article_suffix: ''
title: Zeitlicher Geltungsbereich
sr_number: '311.0'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/54/757_781_799/de#art_2
lexfind_url: ''
in_force_since: ''
layers: {}
