law: ZGB
article: 9
article_suffix: d
title: Art. 9d ZGB
sr_number: '210'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/24/233_245_233/de#art_9d
lexfind_url: ''
in_force_since: ''
layers: {}
