law: OR
article: 964
article_suffix: f
title: Form und Inhalt des Berichts
sr_number: '220'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/27/317_321_377/de#art_964f
lexfind_url: ''
in_force_since: ''
layers: {}
