law: OR
article: 72
article_suffix: ''
title: Wahlobligation
sr_number: '220'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/27/317_321_377/de#art_72
lexfind_url: ''
in_force_since: ''
layers: {}
