law: StGB
article: 386
article_suffix: ''
title: Präventionsmassnahmen
sr_number: '311.0'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/54/757_781_799/de#art_386
lexfind_url: ''
in_force_since: ''
layers: {}
