law: StPO
article: 239
article_suffix: ''
title: Freigabe der Sicherheitsleistung
sr_number: '312.0'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/2010/267/de#art_239
lexfind_url: ''
in_force_since: ''
layers: {}
