law: OR
article: 685
article_suffix: d
title: Voraussetzungen der Ablehnung
sr_number: '220'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/27/317_321_377/de#art_685d
lexfind_url: ''
in_force_since: ''
layers: {}
