law: StGB
article: 327
article_suffix: ''
title: Verletzung der Pflichten zur Meldung der an Aktien oder Stammanteilen wirtschaftlich
  berechtigten Person
sr_number: '311.0'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/54/757_781_799/de#art_327
lexfind_url: ''
in_force_since: ''
layers: {}
