law: ZGB
article: 453
article_suffix: ''
title: Zusammenarbeitspflicht
sr_number: '210'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/24/233_245_233/de#art_453
lexfind_url: ''
in_force_since: ''
layers: {}
