law: OR
article: 656
article_suffix: e
title: Vertretung im Verwaltungsrat
sr_number: '220'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/27/317_321_377/de#art_656e
lexfind_url: ''
in_force_since: ''
layers: {}
