law: BV
article: 129
article_suffix: a
title: Besondere Besteuerung grosser Unternehmensgruppen
sr_number: '101'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/1999/404/de#art_129a
lexfind_url: ''
in_force_since: ''
layers: {}
