law: ZGB
article: 325
article_suffix: ''
title: Entziehung der Verwaltung
sr_number: '210'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/24/233_245_233/de#art_325
lexfind_url: ''
in_force_since: ''
layers: {}
