law: StPO
article: 232
article_suffix: ''
title: Sicherheitshaft während eines Verfahrens vor dem Berufungsgericht
sr_number: '312.0'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/2010/267/de#art_232
lexfind_url: ''
in_force_since: ''
layers: {}
