law: StPO
article: 205
article_suffix: ''
title: Erscheinungspflicht, Verhinderung und Säumnis
sr_number: '312.0'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/2010/267/de#art_205
lexfind_url: ''
in_force_since: ''
layers: {}
