law: BV
article: 121
article_suffix: ''
title: Gesetzgebung im Ausländer- und Asylbereich
sr_number: '101'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/1999/404/de#art_121
lexfind_url: ''
in_force_since: ''
layers:
  caselaw:
    last_generated: '2026-03-23'
    version: 1
    quality_score: 0.91
  doctrine:
    last_generated: '2026-03-23'
    version: 1
    quality_score: 0.9
