law: OR
article: 1136
article_suffix: ''
title: Feiertage
sr_number: '220'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/27/317_321_377/de#art_1136
lexfind_url: ''
in_force_since: ''
layers: {}
