law: OR
article: 539
article_suffix: ''
title: Entzug und Beschränkung der Geschäftsführung
sr_number: '220'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/27/317_321_377/de#art_539
lexfind_url: ''
in_force_since: ''
layers: {}
