law: ZPO
article: 146
article_suffix: ''
title: Wirkungen des Stillstandes
sr_number: '272'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/2010/262/de#art_146
lexfind_url: ''
in_force_since: ''
layers: {}
