law: VwVG
article: 33
article_suffix: b
title: Gütliche Einigung und Mediation
sr_number: '172.021'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/1969/737_757_755/de#art_33b
lexfind_url: ''
in_force_since: ''
layers: {}
