law: StPO
article: 301
article_suffix: ''
title: Anzeigerecht
sr_number: '312.0'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/2010/267/de#art_301
lexfind_url: ''
in_force_since: ''
layers: {}
