law: ZPO
article: 77
article_suffix: ''
title: Wirkungen der Intervention
sr_number: '272'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/2010/262/de#art_77
lexfind_url: ''
in_force_since: ''
layers: {}
