law: BV
article: 121
article_suffix: a
title: Steuerung der Zuwanderung
sr_number: '101'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/1999/404/de#art_121a
lexfind_url: ''
in_force_since: ''
layers: {}
