law: ZPO
article: 228
article_suffix: ''
title: Erste Parteivorträge
sr_number: '272'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/2010/262/de#art_228
lexfind_url: ''
in_force_since: ''
layers: {}
