law: ZPO
article: 332
article_suffix: ''
title: Entscheid über das Revisionsgesuch
sr_number: '272'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/2010/262/de#art_332
lexfind_url: ''
in_force_since: ''
layers: {}
