law: OR
article: 942
article_suffix: ''
title: Rechtsschutz
sr_number: '220'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/27/317_321_377/de#art_942
lexfind_url: ''
in_force_since: ''
layers: {}
