law: ZGB
article: 9
article_suffix: f
title: Art. 9f ZGB
sr_number: '210'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/24/233_245_233/de#art_9f
lexfind_url: ''
in_force_since: ''
layers: {}
