law: StPO
article: 55
article_suffix: ''
title: Zuständigkeit im Allgemeinen
sr_number: '312.0'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/2010/267/de#art_55
lexfind_url: ''
in_force_since: ''
layers: {}
