law: OR
article: 259
article_suffix: i
title: Verfahren
sr_number: '220'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/27/317_321_377/de#art_259i
lexfind_url: ''
in_force_since: ''
layers: {}
