law: StGB
article: 75
article_suffix: a
title: Besondere Sicherheitsmassnahmen
sr_number: '311.0'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/54/757_781_799/de#art_75a
lexfind_url: ''
in_force_since: ''
layers: {}
