law: OR
article: 547
article_suffix: ''
title: Wirkung der Auflösung auf die Geschäftsführung
sr_number: '220'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/27/317_321_377/de#art_547
lexfind_url: ''
in_force_since: ''
layers: {}
