law: OR
article: 687
article_suffix: ''
title: Nicht voll einbezahlte Namenaktien
sr_number: '220'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/27/317_321_377/de#art_687
lexfind_url: ''
in_force_since: ''
layers: {}
