law: StGB
article: 377
article_suffix: ''
title: Pflicht der Kantone zur Errichtung und zum Betrieb
sr_number: '311.0'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/54/757_781_799/de#art_377
lexfind_url: ''
in_force_since: ''
layers: {}
