law: OR
article: 1133
article_suffix: ''
title: Ausfertigung mehrerer Stücke eines Checks
sr_number: '220'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/27/317_321_377/de#art_1133
lexfind_url: ''
in_force_since: ''
layers: {}
