law: StGB
article: 143
article_suffix: bis
title: Unbefugtes Eindringen in ein Datenverarbeitungssystem
sr_number: '311.0'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/54/757_781_799/de#art_143bis
lexfind_url: ''
in_force_since: ''
layers: {}
