law: OR
article: 653
article_suffix: o
title: Änderung der Statuten und Feststellungen des Verwaltungsrats; Eintragung in
  das Handelsregister
sr_number: '220'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/27/317_321_377/de#art_653o
lexfind_url: ''
in_force_since: ''
layers: {}
