law: BV
article: 85
article_suffix: a
title: Abgabe für die Benützung der Nationalstrassen
sr_number: '101'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/1999/404/de#art_85a
lexfind_url: ''
in_force_since: ''
layers: {}
