law: OR
article: 292
article_suffix: ''
title: Übertragung der Pacht auf einen Dritten
sr_number: '220'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/27/317_321_377/de#art_292
lexfind_url: ''
in_force_since: ''
layers: {}
