law: ZPO
article: 402
article_suffix: ''
title: Aufhebung und Änderung bisherigen Rechts
sr_number: '272'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/2010/262/de#art_402
lexfind_url: ''
in_force_since: ''
layers: {}
