law: OR
article: 774
article_suffix: a
title: Genussscheine
sr_number: '220'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/27/317_321_377/de#art_774a
lexfind_url: ''
in_force_since: ''
layers: {}
