law: ZGB
article: 24
article_suffix: ''
title: Wechsel im Wohnsitz oder Aufenthalt
sr_number: '210'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/24/233_245_233/de#art_24
lexfind_url: ''
in_force_since: ''
layers: {}
