law: SchKG
article: 4
article_suffix: a
title: Verfahren in einem sachlichen Zusammenhang
sr_number: '281.1'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/11/529_488_529/de#art_4a
lexfind_url: ''
in_force_since: ''
layers: {}
