law: ZGB
article: 766
article_suffix: ''
title: Zinspflicht bei Nutzniessung an einem Vermögen
sr_number: '210'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/24/233_245_233/de#art_766
lexfind_url: ''
in_force_since: ''
layers: {}
