law: StPO
article: 443
article_suffix: ''
title: Vollstreckung der Strafurteile im Zivilpunkt
sr_number: '312.0'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/2010/267/de#art_443
lexfind_url: ''
in_force_since: ''
layers: {}
