law: OR
article: 961
article_suffix: d
title: Erleichterungen
sr_number: '220'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/27/317_321_377/de#art_961d
lexfind_url: ''
in_force_since: ''
layers: {}
