law: StGB
article: 64
article_suffix: a
title: Aufhebung und Entlassung
sr_number: '311.0'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/54/757_781_799/de#art_64a
lexfind_url: ''
in_force_since: ''
layers: {}
