law: StPO
article: 454
article_suffix: ''
title: Nach Inkrafttreten dieses Gesetzes gefällte Entscheide
sr_number: '312.0'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/2010/267/de#art_454
lexfind_url: ''
in_force_since: ''
layers: {}
