law: BV
article: 103
article_suffix: ''
title: Strukturpolitik
sr_number: '101'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/1999/404/de#art_103
lexfind_url: ''
in_force_since: ''
layers: {}
