law: VwVG
article: 3
article_suffix: ''
title: Unanwendbarkeit
sr_number: '172.021'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/1969/737_757_755/de#art_3
lexfind_url: ''
in_force_since: ''
layers:
  caselaw:
    last_generated: '2026-03-11'
    version: 1
    quality_score: 0.91
  doctrine:
    last_generated: '2026-03-11'
    version: 1
    quality_score: 0.91
  summary:
    last_generated: '2026-03-11'
    version: 1
    quality_score: 0.91
