law: StPO
article: 158
article_suffix: ''
title: Hinweise bei der ersten Einvernahme
sr_number: '312.0'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/2010/267/de#art_158
lexfind_url: ''
in_force_since: ''
layers: {}
