law: ZPO
article: 390
article_suffix: ''
title: Beschwerde an das kantonale Gericht
sr_number: '272'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/2010/262/de#art_390
lexfind_url: ''
in_force_since: ''
layers: {}
