law: SchKG
article: 8
article_suffix: ''
title: Führung, Beweiskraft und Berichtigung
sr_number: '281.1'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/11/529_488_529/de#art_8
lexfind_url: ''
in_force_since: ''
layers: {}
