law: OR
article: 689
article_suffix: e
title: Depotstimmrechtsvertretung in Gesellschaften, deren Aktien nicht an einer Börse
  kotiert sind
sr_number: '220'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/27/317_321_377/de#art_689e
lexfind_url: ''
in_force_since: ''
layers: {}
