law: StPO
article: 54
article_suffix: ''
title: Anwendbarkeit dieses Gesetzes
sr_number: '312.0'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/2010/267/de#art_54
lexfind_url: ''
in_force_since: ''
layers: {}
