law: ZPO
article: 179
article_suffix: ''
title: Beweiskraft öffentlicher Register und Urkunden
sr_number: '272'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/2010/262/de#art_179
lexfind_url: ''
in_force_since: ''
layers: {}
