law: SchKG
article: 255
article_suffix: a
title: Zirkularbeschluss
sr_number: '281.1'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/11/529_488_529/de#art_255a
lexfind_url: ''
in_force_since: ''
layers: {}
