law: StGB
article: 11
article_suffix: ''
title: Begehen durch Unterlassen
sr_number: '311.0'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/54/757_781_799/de#art_11
lexfind_url: ''
in_force_since: ''
layers: {}
