law: BV
article: 13
article_suffix: ''
title: Schutz der Privatsphäre
sr_number: '101'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/1999/404/de#art_13
lexfind_url: ''
in_force_since: ''
layers: {}
