law: StPO
article: 8
article_suffix: ''
title: Verzicht auf Strafverfolgung
sr_number: '312.0'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/2010/267/de#art_8
lexfind_url: ''
in_force_since: ''
layers: {}
