law: ZPO
article: 37
article_suffix: ''
title: Schadenersatz bei ungerechtfertigten vorsorglichen Massnahmen
sr_number: '272'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/2010/262/de#art_37
lexfind_url: ''
in_force_since: ''
layers: {}
