law: StGB
article: 161
article_suffix: bis
title: Hehlerei
sr_number: '311.0'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/54/757_781_799/de#art_161bis
lexfind_url: ''
in_force_since: ''
layers: {}
