law: OR
article: 1072
article_suffix: ''
title: Vorsorgliche Massnahmen
sr_number: '220'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/27/317_321_377/de#art_1072
lexfind_url: ''
in_force_since: ''
layers: {}
