law: ZGB
article: 89
article_suffix: ''
title: Antrags- und Klagerecht, Löschung im Register
sr_number: '210'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/24/233_245_233/de#art_89
lexfind_url: ''
in_force_since: ''
layers: {}
