law: BV
article: 149
article_suffix: ''
title: Zusammensetzung und Wahl des Nationalrates
sr_number: '101'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/1999/404/de#art_149
lexfind_url: ''
in_force_since: ''
layers: {}
