law: VwVG
article: 78
article_suffix: ''
title: Als einzige oder erste Instanz
sr_number: '172.021'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/1969/737_757_755/de#art_78
lexfind_url: ''
in_force_since: ''
layers: {}
