law: StPO
article: 164
article_suffix: ''
title: Abklärungen über die Zeugin oder den Zeugen
sr_number: '312.0'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/2010/267/de#art_164
lexfind_url: ''
in_force_since: ''
layers: {}
