law: BV
article: 196
article_suffix: ''
title: Übergangsbestimmungen gemäss Bundesbeschluss vom 18. Dezember 1998 über eine
  neue Bundesverfassung
sr_number: '101'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/1999/404/de#art_196
lexfind_url: ''
in_force_since: ''
layers: {}
