law: SchKG
article: 94
article_suffix: ''
title: Pfändung von Früchten vor der Ernte
sr_number: '281.1'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/11/529_488_529/de#art_94
lexfind_url: ''
in_force_since: ''
layers: {}
