law: BV
article: 48
article_suffix: a
title: Allgemeinverbindlicherklärung und Beteiligungspflicht
sr_number: '101'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/1999/404/de#art_48a
lexfind_url: ''
in_force_since: ''
layers: {}
