law: OR
article: 684
article_suffix: a
title: Bei überschuldeten Gesellschaften ohne Geschäftstätigkeit und ohne Aktiven
sr_number: '220'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/27/317_321_377/de#art_684a
lexfind_url: ''
in_force_since: ''
layers: {}
