law: OR
article: 964
article_suffix: c
title: Genehmigung, Veröffentlichung, Führung und Aufbewahrung
sr_number: '220'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/27/317_321_377/de#art_964c
lexfind_url: ''
in_force_since: ''
layers: {}
