law: BV
article: 25
article_suffix: ''
title: Schutz vor Ausweisung, Auslieferung und Ausschaffung
sr_number: '101'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/1999/404/de#art_25
lexfind_url: ''
in_force_since: ''
layers: {}
