law: OR
article: 299
article_suffix: a
title: Prüfung der Sache und Meldung an den Pächter
sr_number: '220'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/27/317_321_377/de#art_299a
lexfind_url: ''
in_force_since: ''
layers: {}
