law: ZPO
article: 76
article_suffix: ''
title: Rechte der intervenierenden Person
sr_number: '272'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/2010/262/de#art_76
lexfind_url: ''
in_force_since: ''
layers: {}
