law: ZGB
article: 842
article_suffix: ''
title: Zweck; Verhältnis zur Forderung aus dem Grundverhältnis
sr_number: '210'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/24/233_245_233/de#art_842
lexfind_url: ''
in_force_since: ''
layers: {}
