law: ZGB
article: 692
article_suffix: ''
title: Wahrung der Interessen des Belasteten
sr_number: '210'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/24/233_245_233/de#art_692
lexfind_url: ''
in_force_since: ''
layers: {}
