law: ZGB
article: 1
article_suffix: ''
title: Anwendung des Rechts
sr_number: '210'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/24/233_245_233/de#art_1
lexfind_url: ''
in_force_since: ''
layers: {}
