law: OR
article: 689
article_suffix: a
title: Berechtigung gegenüber der Gesellschaft
sr_number: '220'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/27/317_321_377/de#art_689a
lexfind_url: ''
in_force_since: ''
layers: {}
