law: StGB
article: 239
article_suffix: ''
title: Störung von Betrieben im Dienste der Allgemeinheit
sr_number: '311.0'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/54/757_781_799/de#art_239
lexfind_url: ''
in_force_since: ''
layers: {}
