law: StPO
article: 155
article_suffix: ''
title: Massnahmen zum Schutz von Personen mit einer psychischen Störung
sr_number: '312.0'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/2010/267/de#art_155
lexfind_url: ''
in_force_since: ''
layers: {}
