law: OR
article: 697
article_suffix: b
title: Ablehnung des Begehrens um Auskunft oder Einsicht
sr_number: '220'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/27/317_321_377/de#art_697b
lexfind_url: ''
in_force_since: ''
layers: {}
