law: BV
article: 166
article_suffix: ''
title: Beziehungen zum Ausland und völkerrechtliche Verträge
sr_number: '101'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/1999/404/de#art_166
lexfind_url: ''
in_force_since: ''
layers: {}
