law: OR
article: 336
article_suffix: d
title: durch den Arbeitnehmer
sr_number: '220'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/27/317_321_377/de#art_336d
lexfind_url: ''
in_force_since: ''
layers: {}
