law: OR
article: 167
article_suffix: ''
title: Zahlung in gutem Glauben
sr_number: '220'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/27/317_321_377/de#art_167
lexfind_url: ''
in_force_since: ''
layers: {}
