law: OR
article: 1088
article_suffix: ''
title: Handlungen zur Ausübung und Erhaltung des Wechselrechts
sr_number: '220'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/27/317_321_377/de#art_1088
lexfind_url: ''
in_force_since: ''
layers: {}
