law: StPO
article: 90
article_suffix: ''
title: Beginn und Berechnung der Fristen
sr_number: '312.0'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/2010/267/de#art_90
lexfind_url: ''
in_force_since: ''
layers: {}
