law: ZGB
article: 59
article_suffix: ''
title: Vorbehalt des öffentlichen und des Gesellschafts- und Genossenschaftsrechtes
sr_number: '210'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/24/233_245_233/de#art_59
lexfind_url: ''
in_force_since: ''
layers: {}
