law: StGB
article: 278
article_suffix: ''
title: Störung des Militärdienstes
sr_number: '311.0'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/54/757_781_799/de#art_278
lexfind_url: ''
in_force_since: ''
layers: {}
