law: VwVG
article: 71
article_suffix: ''
title: Aufsichtsbeschwerde
sr_number: '172.021'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/1969/737_757_755/de#art_71
lexfind_url: ''
in_force_since: ''
layers: {}
