law: SchKG
article: 95
article_suffix: a
title: Forderungen gegen den Ehegatten, die eingetragene Partnerin oder den eingetragenen
  Partner
sr_number: '281.1'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/11/529_488_529/de#art_95a
lexfind_url: ''
in_force_since: ''
layers: {}
