law: OR
article: 393
article_suffix: ''
title: Bearbeitung eines Werkes nach Plan des Verlegers
sr_number: '220'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/27/317_321_377/de#art_393
lexfind_url: ''
in_force_since: ''
layers: {}
