law: OR
article: 36
article_suffix: ''
title: Rückgabe der Vollmachtsurkunde
sr_number: '220'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/27/317_321_377/de#art_36
lexfind_url: ''
in_force_since: ''
layers: {}
