law: ZPO
article: 94
article_suffix: a
title: 'Titel:  Streitwert'
sr_number: '272'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/2010/262/de#art_94a
lexfind_url: ''
in_force_since: ''
layers: {}
