law: BV
article: 56
article_suffix: ''
title: Beziehungen der Kantone mit dem Ausland
sr_number: '101'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/1999/404/de#art_56
lexfind_url: ''
in_force_since: ''
layers: {}
