law: BV
article: 119
article_suffix: ''
title: Fortpflanzungsmedizin und Gentechnologie im Humanbereich
sr_number: '101'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/1999/404/de#art_119
lexfind_url: ''
in_force_since: ''
layers: {}
