law: OR
article: 825
article_suffix: ''
title: Anspruch und Höhe
sr_number: '220'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/27/317_321_377/de#art_825
lexfind_url: ''
in_force_since: ''
layers: {}
