law: ZPO
article: 349
article_suffix: ''
title: Urkunde über eine Geldleistung
sr_number: '272'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/2010/262/de#art_349
lexfind_url: ''
in_force_since: ''
layers: {}
