law: BV
article: 47
article_suffix: ''
title: Eigenständigkeit der Kantone
sr_number: '101'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/1999/404/de#art_47
lexfind_url: ''
in_force_since: ''
layers:
  caselaw:
    last_generated: '2026-03-22'
    version: 2
    quality_score: 0.9
  doctrine:
    last_generated: '2026-04-13'
    version: 4
    quality_score: 0.91
