law: ZGB
article: 949
article_suffix: c
title: Landesweite Grundstücksuche
sr_number: '210'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/24/233_245_233/de#art_949c
lexfind_url: ''
in_force_since: ''
layers: {}
