law: OR
article: 815
article_suffix: ''
title: Abberufung von Geschäftsführern; Entziehung der Vertretungsbefugnis
sr_number: '220'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/27/317_321_377/de#art_815
lexfind_url: ''
in_force_since: ''
layers: {}
