law: BV
article: 139
article_suffix: ''
title: Volksinitiative auf Teilrevision der Bundesverfassung
sr_number: '101'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/1999/404/de#art_139
lexfind_url: ''
in_force_since: ''
layers: {}
