law: ZGB
article: 544
article_suffix: ''
title: Das Kind vor der Geburt
sr_number: '210'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/24/233_245_233/de#art_544
lexfind_url: ''
in_force_since: ''
layers: {}
