law: OR
article: 734
article_suffix: f
title: Vertretung der Geschlechter im Verwaltungsrat und in der Geschäftsleitung
sr_number: '220'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/27/317_321_377/de#art_734f
lexfind_url: ''
in_force_since: ''
layers: {}
