law: OR
article: 211
article_suffix: ''
title: Zahlung des Preises und Annahme der Kaufsache
sr_number: '220'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/27/317_321_377/de#art_211
lexfind_url: ''
in_force_since: ''
layers: {}
