law: VwVG
article: 11
article_suffix: ''
title: Im Allgemeinen
sr_number: '172.021'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/1969/737_757_755/de#art_11
lexfind_url: ''
in_force_since: ''
layers: {}
