law: ZGB
article: 742
article_suffix: ''
title: Verlegung der Belastung
sr_number: '210'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/24/233_245_233/de#art_742
lexfind_url: ''
in_force_since: ''
layers: {}
