law: ZGB
article: 420
article_suffix: ''
title: 'Achter Unterabschnitt:  Besondere Bestimmungen für Angehörige'
sr_number: '210'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/24/233_245_233/de#art_420
lexfind_url: ''
in_force_since: ''
layers: {}
