law: StGB
article: 179
article_suffix: septies
title: Missbrauch einer Fernmeldeanlage
sr_number: '311.0'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/54/757_781_799/de#art_179septies
lexfind_url: ''
in_force_since: ''
layers: {}
