law: StPO
article: 298
article_suffix: c
title: Anforderungen an die eingesetzten Personen und Durchführung
sr_number: '312.0'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/2010/267/de#art_298c
lexfind_url: ''
in_force_since: ''
layers: {}
