law: ZPO
article: 187
article_suffix: ''
title: Erstattung des Gutachtens
sr_number: '272'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/2010/262/de#art_187
lexfind_url: ''
in_force_since: ''
layers: {}
