law: ZPO
article: 346
article_suffix: ''
title: Rechtsmittel Dritter
sr_number: '272'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/2010/262/de#art_346
lexfind_url: ''
in_force_since: ''
layers: {}
