law: StGB
article: 355
article_suffix: e
title: SIRENE-Büro
sr_number: '311.0'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/54/757_781_799/de#art_355e
lexfind_url: ''
in_force_since: ''
layers: {}
