law: SchKG
article: 193
article_suffix: ''
title: Gegen eine ausgeschlagene oder überschuldete Erbschaft
sr_number: '281.1'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/11/529_488_529/de#art_193
lexfind_url: ''
in_force_since: ''
layers: {}
