law: StGB
article: 349
article_suffix: d
title: Bekanntgabe von Personendaten aus einem Schengen-Staat an einen Drittstaat
  oder an ein internationales Organ
sr_number: '311.0'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/54/757_781_799/de#art_349d
lexfind_url: ''
in_force_since: ''
layers: {}
