law: ZGB
article: 70
article_suffix: ''
title: Ein- und Austritt
sr_number: '210'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/24/233_245_233/de#art_70
lexfind_url: ''
in_force_since: ''
layers: {}
