law: BV
article: 61
article_suffix: a
title: Bildungsraum Schweiz
sr_number: '101'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/1999/404/de#art_61a
lexfind_url: ''
in_force_since: ''
layers: {}
