law: StGB
article: 225
article_suffix: ''
title: Gefährdung ohne verbrecherische Absicht und fahrlässige Gefährdung
sr_number: '311.0'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/54/757_781_799/de#art_225
lexfind_url: ''
in_force_since: ''
layers: {}
