law: OR
article: 610
article_suffix: ''
title: Klagerecht der Gläubiger
sr_number: '220'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/27/317_321_377/de#art_610
lexfind_url: ''
in_force_since: ''
layers: {}
