law: StPO
article: 153
article_suffix: ''
title: Besondere Massnahmen zum Schutz von Opfern von Straftaten gegen die sexuelle
  Integrität
sr_number: '312.0'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/2010/267/de#art_153
lexfind_url: ''
in_force_since: ''
layers: {}
