law: ZPO
article: 308
article_suffix: ''
title: Anfechtbare Entscheide
sr_number: '272'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/2010/262/de#art_308
lexfind_url: ''
in_force_since: ''
layers: {}
