law: OR
article: 762
article_suffix: ''
title: 'Siebenter Abschnitt:  Beteiligung von Körperschaften des öffentlichen Rechts'
sr_number: '220'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/27/317_321_377/de#art_762
lexfind_url: ''
in_force_since: ''
layers: {}
