law: StPO
article: 36
article_suffix: ''
title: Gerichtsstand bei Betreibungs- und Konkursdelikten und bei Strafverfahren gegen
  Unternehmen
sr_number: '312.0'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/2010/267/de#art_36
lexfind_url: ''
in_force_since: ''
layers: {}
