law: ZGB
article: 184
article_suffix: ''
title: Form des Vertrages
sr_number: '210'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/24/233_245_233/de#art_184
lexfind_url: ''
in_force_since: ''
layers: {}
