law: OR
article: 958
article_suffix: b
title: Zeitliche und sachliche Abgrenzung
sr_number: '220'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/27/317_321_377/de#art_958b
lexfind_url: ''
in_force_since: ''
layers: {}
