law: StPO
article: 427
article_suffix: ''
title: Kostentragungspflicht der Privatklägerschaft und der antragstellenden Person
sr_number: '312.0'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/2010/267/de#art_427
lexfind_url: ''
in_force_since: ''
layers: {}
