law: ZPO
article: 389
article_suffix: ''
title: Beschwerde an das Bundesgericht
sr_number: '272'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/2010/262/de#art_389
lexfind_url: ''
in_force_since: ''
layers: {}
