law: StGB
article: 260
article_suffix: quinquies
title: Finanzierung des Terrorismus
sr_number: '311.0'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/54/757_781_799/de#art_260quinquies
lexfind_url: ''
in_force_since: ''
layers: {}
