law: ZGB
article: 9
article_suffix: g
title: Art. 9g ZGB
sr_number: '210'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/24/233_245_233/de#art_9g
lexfind_url: ''
in_force_since: ''
layers: {}
