law: OR
article: 1073
article_suffix: ''
title: Bekannter Inhaber
sr_number: '220'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/27/317_321_377/de#art_1073
lexfind_url: ''
in_force_since: ''
layers: {}
