law: OR
article: 355
article_suffix: ''
title: Anwendbarkeit der allgemeinen Vorschriften
sr_number: '220'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/27/317_321_377/de#art_355
lexfind_url: ''
in_force_since: ''
layers: {}
