law: StGB
article: 349
article_suffix: g
title: Prüfung der Rechtmässigkeit der Datenbearbeitung
sr_number: '311.0'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/54/757_781_799/de#art_349g
lexfind_url: ''
in_force_since: ''
layers: {}
