law: OR
article: 207
article_suffix: ''
title: Wandelung bei Untergang der Sache
sr_number: '220'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/27/317_321_377/de#art_207
lexfind_url: ''
in_force_since: ''
layers: {}
