law: OR
article: 1091
article_suffix: ''
title: Teilannahme und Teilzahlung
sr_number: '220'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/27/317_321_377/de#art_1091
lexfind_url: ''
in_force_since: ''
layers: {}
