law: StGB
article: 67
article_suffix: d
title: Änderung eines Verbots oder nachträgliche Anordnung eines Verbots
sr_number: '311.0'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/54/757_781_799/de#art_67d
lexfind_url: ''
in_force_since: ''
layers: {}
