law: ZGB
article: 682
article_suffix: ''
title: Im Miteigentums- und im Baurechtsverhältnis
sr_number: '210'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/24/233_245_233/de#art_682
lexfind_url: ''
in_force_since: ''
layers: {}
