law: ZGB
article: 516
article_suffix: ''
title: Verfügungsbeschränkung
sr_number: '210'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/24/233_245_233/de#art_516
lexfind_url: ''
in_force_since: ''
layers: {}
