law: StPO
article: 224
article_suffix: ''
title: Haftverfahren vor der Staatsanwaltschaft
sr_number: '312.0'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/2010/267/de#art_224
lexfind_url: ''
in_force_since: ''
layers: {}
