law: ZGB
article: 255
article_suffix: a
title: Elternschaft der Ehefrau
sr_number: '210'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/24/233_245_233/de#art_255a
lexfind_url: ''
in_force_since: ''
layers: {}
