law: StGB
article: 175
article_suffix: ''
title: Üble Nachrede oder Verleumdung gegen einen Verstorbenen oder einen verschollen
  Erklärten
sr_number: '311.0'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/54/757_781_799/de#art_175
lexfind_url: ''
in_force_since: ''
layers: {}
