law: StPO
article: 233
article_suffix: ''
title: Haftentlassungsgesuch während eines Verfahrens vor dem Berufungsgericht
sr_number: '312.0'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/2010/267/de#art_233
lexfind_url: ''
in_force_since: ''
layers: {}
