law: StGB
article: 266
article_suffix: ''
title: Angriffe auf die Unabhängigkeit der Eidgenossenschaft
sr_number: '311.0'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/54/757_781_799/de#art_266
lexfind_url: ''
in_force_since: ''
layers: {}
