law: StPO
article: 179
article_suffix: ''
title: Auskunftspersonen bei polizeilichen Einvernahmen
sr_number: '312.0'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/2010/267/de#art_179
lexfind_url: ''
in_force_since: ''
layers: {}
