law: VwVG
article: 48
article_suffix: ''
title: Beschwerdelegitimation
sr_number: '172.021'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/1969/737_757_755/de#art_48
lexfind_url: ''
in_force_since: ''
layers: {}
