law: StGB
article: 248
article_suffix: ''
title: Fälschung von Mass und Gewicht
sr_number: '311.0'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/54/757_781_799/de#art_248
lexfind_url: ''
in_force_since: ''
layers: {}
