law: StGB
article: 261
article_suffix: ''
title: Störung der Glaubens- und Kultusfreiheit
sr_number: '311.0'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/54/757_781_799/de#art_261
lexfind_url: ''
in_force_since: ''
layers: {}
