law: OR
article: 990
article_suffix: ''
title: Wechselfähigkeit
sr_number: '220'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/27/317_321_377/de#art_990
lexfind_url: ''
in_force_since: ''
layers: {}
