law: StPO
article: 46
article_suffix: ''
title: Direkter Geschäftsverkehr
sr_number: '312.0'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/2010/267/de#art_46
lexfind_url: ''
in_force_since: ''
layers: {}
