law: OR
article: 653
article_suffix: u
title: Erhöhung und Herabsetzung des Aktienkapitals innerhalb des Kapitalbands
sr_number: '220'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/27/317_321_377/de#art_653u
lexfind_url: ''
in_force_since: ''
layers: {}
