law: BV
article: 86
article_suffix: ''
title: Verwendung von Abgaben für Aufgaben und Aufwendungen im Zusammenhang mit dem
  Strassenverkehr
sr_number: '101'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/1999/404/de#art_86
lexfind_url: ''
in_force_since: ''
layers: {}
