law: StPO
article: 23
article_suffix: ''
title: Bundesgerichtsbarkeit im Allgemeinen
sr_number: '312.0'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/2010/267/de#art_23
lexfind_url: ''
in_force_since: ''
layers: {}
