law: OR
article: 297
article_suffix: a
title: Konkurs des Pächters
sr_number: '220'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/27/317_321_377/de#art_297a
lexfind_url: ''
in_force_since: ''
layers: {}
