law: StPO
article: 160
article_suffix: ''
title: Einvernahme einer geständigen beschuldigten Person
sr_number: '312.0'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/2010/267/de#art_160
lexfind_url: ''
in_force_since: ''
layers: {}
