law: StPO
article: 261
article_suffix: ''
title: 'Kapitel:  Erkennungsdienstliche Erfassung, Schrift- und Sprachproben'
sr_number: '312.0'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/2010/267/de#art_261
lexfind_url: ''
in_force_since: ''
layers: {}
