law: StPO
article: 96
article_suffix: ''
title: Bekanntgabe und Verwendung bei hängigem Strafverfahren
sr_number: '312.0'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/2010/267/de#art_96
lexfind_url: ''
in_force_since: ''
layers: {}
