law: BV
article: 179
article_suffix: ''
title: Bundeskanzlei
sr_number: '101'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/1999/404/de#art_179
lexfind_url: ''
in_force_since: ''
layers: {}
