law: StPO
article: 431
article_suffix: ''
title: Entschädigung und Genugtuung wegen rechtswidrig angewandter Zwangsmassnahmen
  und überlanger Haft
sr_number: '312.0'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/2010/267/de#art_431
lexfind_url: ''
in_force_since: ''
layers: {}
