law: StGB
article: 264
article_suffix: n
title: Ausschluss der relativen Immunität
sr_number: '311.0'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/54/757_781_799/de#art_264n
lexfind_url: ''
in_force_since: ''
layers: {}
