law: StGB
article: 243
article_suffix: ''
title: Nachmachen von Banknoten, Münzen oder amtlichen Wertzeichen ohne Fälschungsabsicht
sr_number: '311.0'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/54/757_781_799/de#art_243
lexfind_url: ''
in_force_since: ''
layers: {}
