law: BV
article: 60
article_suffix: ''
title: Organisation, Ausbildung und Ausrüstung der Armee
sr_number: '101'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/1999/404/de#art_60
lexfind_url: ''
in_force_since: ''
layers: {}
