law: StPO
article: 388
article_suffix: ''
title: Zuständigkeit der Verfahrensleitung für verfahrensleitende und vorsorgliche
  Massnahmen sowie Nichteintretensentscheide
sr_number: '312.0'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/2010/267/de#art_388
lexfind_url: ''
in_force_since: ''
layers: {}
