law: ZGB
article: 301
article_suffix: a
title: Bestimmung des Aufenthaltsortes
sr_number: '210'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/24/233_245_233/de#art_301a
lexfind_url: ''
in_force_since: ''
layers: {}
