law: StPO
article: 411
article_suffix: ''
title: Form und Frist
sr_number: '312.0'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/2010/267/de#art_411
lexfind_url: ''
in_force_since: ''
layers: {}
