law: SchKG
article: 11
article_suffix: ''
title: Beamte und Angestellte der Betreibungs- und der Konkursämter
sr_number: '281.1'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/11/529_488_529/de#art_11
lexfind_url: ''
in_force_since: ''
layers: {}
