law: OR
article: 856
article_suffix: ''
title: Bekanntmachung des Geschäftsberichts
sr_number: '220'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/27/317_321_377/de#art_856
lexfind_url: ''
in_force_since: ''
layers: {}
