law: StGB
article: 305
article_suffix: ''
title: Begünstigung
sr_number: '311.0'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/54/757_781_799/de#art_305
lexfind_url: ''
in_force_since: ''
layers: {}
