law: OR
article: 392
article_suffix: ''
title: Endigungsgründe in der Person des Urhebers und des Verlegers
sr_number: '220'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/27/317_321_377/de#art_392
lexfind_url: ''
in_force_since: ''
layers: {}
