law: OR
article: 734
article_suffix: e
title: Tätigkeiten bei anderen Unternehmen
sr_number: '220'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/27/317_321_377/de#art_734e
lexfind_url: ''
in_force_since: ''
layers: {}
