law: ZGB
article: 298
article_suffix: e
title: Veränderung der Verhältnisse nach Stiefkindadoption in faktischen Lebensgemeinschaften
sr_number: '210'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/24/233_245_233/de#art_298e
lexfind_url: ''
in_force_since: ''
layers: {}
