law: ZPO
article: 252
article_suffix: ''
title: Gesuch
sr_number: '272'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/2010/262/de#art_252
lexfind_url: ''
in_force_since: ''
layers: {}
