law: OR
article: 963
article_suffix: a
title: Befreiung von der Pflicht zur Erstellung
sr_number: '220'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/27/317_321_377/de#art_963a
lexfind_url: ''
in_force_since: ''
layers: {}
