law: StGB
article: 317
article_suffix: bis
title: Nicht strafbare Handlungen
sr_number: '311.0'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/54/757_781_799/de#art_317bis
lexfind_url: ''
in_force_since: ''
layers: {}
