law: BV
article: 108
article_suffix: ''
title: Wohnbau- und Wohneigentumsförderung
sr_number: '101'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/1999/404/de#art_108
lexfind_url: ''
in_force_since: ''
layers: {}
