law: SchKG
article: 85
article_suffix: a
title: Im ordentlichen und im vereinfachten Verfahren
sr_number: '281.1'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/11/529_488_529/de#art_85a
lexfind_url: ''
in_force_since: ''
layers: {}
