law: OR
article: 985
article_suffix: ''
title: Bei Vorlegung der Urkunde
sr_number: '220'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/27/317_321_377/de#art_985
lexfind_url: ''
in_force_since: ''
layers: {}
