law: OR
article: 987
article_suffix: ''
title: Bei Coupons im besondern
sr_number: '220'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/27/317_321_377/de#art_987
lexfind_url: ''
in_force_since: ''
layers: {}
