law: StGB
article: 66
article_suffix: abis
title: Art. 66abis StGB
sr_number: '311.0'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/54/757_781_799/de#art_66abis
lexfind_url: ''
in_force_since: ''
layers: {}
