law: OR
article: 339
article_suffix: b
title: Voraussetzungen
sr_number: '220'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/27/317_321_377/de#art_339b
lexfind_url: ''
in_force_since: ''
layers: {}
