law: BV
article: 99
article_suffix: ''
title: Geld- und Währungspolitik
sr_number: '101'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/1999/404/de#art_99
lexfind_url: ''
in_force_since: ''
layers: {}
