law: OR
article: 375
article_suffix: ''
title: Rücktritt wegen Überschreitung des Kostenansatzes
sr_number: '220'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/27/317_321_377/de#art_375
lexfind_url: ''
in_force_since: ''
layers: {}
