law: StGB
article: 259
article_suffix: ''
title: Öffentliche Aufforderung zu Verbrechen oder zur Gewalttätigkeit
sr_number: '311.0'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/54/757_781_799/de#art_259
lexfind_url: ''
in_force_since: ''
layers: {}
