law: BGFA
article: 13
article_suffix: ''
title: Berufsgeheimnis
sr_number: '935.61'
absatz_count: 2
fedlex_url: https://www.fedlex.admin.ch/eli/cc/2002/153/de#art_13
lexfind_url: ''
in_force_since: ''
layers:
  summary:
    last_generated: '2026-04-06'
    version: 1
  doctrine:
    last_generated: '2026-04-13'
    version: 3
    quality_score: 0.8
  caselaw:
    last_generated: '2026-04-06'
    version: 1
