law: ZGB
article: 276
article_suffix: a
title: Vorrang der Unterhaltspflicht gegenüber einem minderjährigen Kind
sr_number: '210'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/24/233_245_233/de#art_276a
lexfind_url: ''
in_force_since: ''
layers: {}
