law: StGB
article: 166
article_suffix: ''
title: Unterlassung der Buchführung
sr_number: '311.0'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/54/757_781_799/de#art_166
lexfind_url: ''
in_force_since: ''
layers: {}
