law: ZGB
article: 372
article_suffix: ''
title: Eintritt der Urteilsunfähigkeit
sr_number: '210'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/24/233_245_233/de#art_372
lexfind_url: ''
in_force_since: ''
layers: {}
