law: OR
article: 266
article_suffix: l
title: Im Allgemeinen
sr_number: '220'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/27/317_321_377/de#art_266l
lexfind_url: ''
in_force_since: ''
layers: {}
