law: OR
article: 335
article_suffix: k
title: Während eines Konkurs- oder eines Nachlassverfahrens
sr_number: '220'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/27/317_321_377/de#art_335k
lexfind_url: ''
in_force_since: ''
layers: {}
