law: ZPO
article: 122
article_suffix: ''
title: Liquidation der Prozesskosten
sr_number: '272'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/2010/262/de#art_122
lexfind_url: ''
in_force_since: ''
layers: {}
