law: StGB
article: 162
article_suffix: ''
title: Verletzung des Fabrikations- oder Geschäftsgeheimnisses
sr_number: '311.0'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/54/757_781_799/de#art_162
lexfind_url: ''
in_force_since: ''
layers: {}
