law: StPO
article: 207
article_suffix: ''
title: Voraussetzungen und Zuständigkeit
sr_number: '312.0'
absatz_count: 1
fedlex_url: https://www.fedlex.admin.ch/eli/cc/2010/267/de#art_207
lexfind_url: ''
in_force_since: ''
layers: {}
